### ISSUE TITLE
Unix中control J与control M的区别？

### ISSUE THREAD

**Issue by justtio** [woota/frontend-discussion#2]
### 图片一
![default](https://user-images.githubusercontent.com/24400225/48658901-4c362680-ea84-11e8-953e-9df292a18ade.jpeg)
### 图片二
![default](https://user-images.githubusercontent.com/24400225/48658909-738cf380-ea84-11e8-8533-a267677f3df4.jpeg)
### 图片三
![default](https://user-images.githubusercontent.com/24400225/48658914-7e478880-ea84-11e8-9023-18c18c7778dc.jpeg)

---
### 我有两个问题：
1.书上说`换行字符=control J`，`返回字符=control M`，但是在`terminal`上显示好像二者并没有什么区别。他们有分别属于自己的功能么？

2.现在mac键盘上`return`键是**映射**（等于）`control J`还是`control M`还是`control J+control M`？

**Comment by justtio** [comment]
> 1. **^M** 对应的是 CR(Carriage Return)，中文意思是托盘的返回。**^J** 对应的是 LF(Line Feed)，中文意思是另起一行。二者的区别在于，**^M** 是让打印头（源自老式的打印机）重新回到最左边的位置，而 **^J** 是让纸张向上移动一行，两个指令不一样。
> 2. 现在电脑的键盘，包括 Mac 的键盘中的 **Return** 对应的都是 **^M** + **^J**，敲下 **Return** 键，光标（对应老式打印机的打印头）会回到最左边（^M），而且也会新起一行（^J）。

但是这个两个命令在终端上显示出来的效果是一模一样的，敲下**^M**命令也会换行，这是否说明这俩个命令在终端命令功能上没有差别？

**Comment by justtio** [comment]
噢，懂了，也就是说终端会自动补全另一个命令是么？

**Comment by woota** [comment]
> > 1. **^M** 对应的是 CR(Carriage Return)，中文意思是托盘的返回。**^J** 对应的是 LF(Line Feed)，中文意思是另起一行。二者的区别在于，**^M** 是让打印头（源自老式的打印机）重新回到最左边的位置，而 **^J** 是让纸张向上移动一行，两个指令不一样。
> > 2. 现在电脑的键盘，包括 Mac 的键盘中的 **Return** 对应的都是 **^M** + **^J**，敲下 **Return** 键，光标（对应老式打印机的打印头）会回到最左边（^M），而且也会新起一行（^J）。
> 
> 但是这个两个命令在终端上显示出来的效果是一模一样的，敲下(^M)命令也会换行，这是否说明这俩个命令在终端命令功能上没有差别？
> ![image](https://user-images.githubusercontent.com/24400225/48661570-ead77d00-eaae-11e8-9cea-01c2f9f2f0a0.png)

# 分析（根据实际结果猜测）：
1. 当在终端输入 ^M ，系统 **转换** 为 ^J 写入；
2. 当在终端输入 ^J，系统 **不转换** 也以 ^J 写入；
3. 当在终端输入 Return ，系统发送 ^M ，同样 **转换** 为 ^J 写入；
（因此在 Unix 文件系中，只会存在 ^J 字符。）
3. 在回显的时候，遇到 ^J 统统 **转换** 为 ^M^J 显示。
